server:
  mode: 'debug'
  port: '8080'
  defaultPageSize: 20 # 默认分页条数
  maxPageSize: 500    # 最大分页条数
jwt:
  tokenExpire: 36000   # token过期时间
  tokenKey: 'Authorization' # token的键名
  tokenIssuer: 'go-start'
  jwtSecret: 'LIXLolf0ZJ8qalcwh5FQi5xrzjJQHLpy'
redoc:
  title: "GoStart OpenApi"
  desc: "生成项目的接口文档信息"
  docPath: "/api/redoc"
  specPath: "/api/swagger.json"
  specFile: "./swagger.json"
log:
  debug: true
  fileName: 'go-start' # 日志文件名称
  dirPath: 'storage/logs/' # 日志默认存放目录
database:
  driver: 'mysql'
  host: '127.0.0.1'
  port: '3306'
  user: 'root'
  password: 'root'
  dbName: 'go_start'
redis:
  host: '127.0.0.1'
  port: '6379'
  password: ''
  dbNum: 0
  loginPrefix: 'go_start_login_' # 登录用户存入redis键名的前缀