
###
POST http://localhost:8088/backend/admin/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTAwMDAsImV4cCI6MTY3OTU5OTc1Nn0.31Wv7RWMEQuq2lwF7AGxyZw0NsscEp54GEsYhBnxLmc

{
  "phone": "15105191181",
  "nickname": "Jack",
  "email": "892774306@qq.com",
  "password": "12345"
}

###
POST http://localhost:8088/backend/admin/sign-in
Content-Type: application/json

{
  "email": "892774306@qq.com",
  "password": "12345"
}

###
###
GET http://localhost:8088/api/user/profile
Content-Type: application/json

{
  "phone": "15105191181",
  "password": "12345"
}

###
GET http://localhost:8088/api/user/profile/7
Accept: application/json
#Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZXhwIjoxNjc5NTc5OTIwfQ.t3ucCMXnfZ9Dq0Dbrs-d1VEweEGer0OuxGqOelICqrs

